// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using project1.Data.datamodel;

namespace project1.Data.datamodel
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("project1.Data.datamodel.model1", b =>
                {
                    b.Property<int>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("GroupDetail")
                        .HasColumnType("text");

                    b.Property<string>("Hiragana")
                        .HasColumnType("text");

                    b.Property<string>("InEnglish")
                        .HasColumnType("text");

                    b.Property<string>("InMyanmar")
                        .HasColumnType("text");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<string>("Romaji")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Vocab")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WordGroup")
                        .HasColumnType("text");

                    b.HasKey("Key");

                    b.ToTable("model1data");
                });

            modelBuilder.Entity("project1.Data.datamodel.model2", b =>
                {
                    b.Property<int>("ExampleKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("InEnglish")
                        .HasColumnType("text");

                    b.Property<string>("InMyanmar")
                        .HasColumnType("text");

                    b.Property<int>("Model1Key")
                        .HasColumnType("integer");

                    b.Property<string>("Sentence")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("ExampleKey");

                    b.HasIndex("Model1Key");

                    b.ToTable("model2data");
                });

            modelBuilder.Entity("project1.Data.datamodel.model2", b =>
                {
                    b.HasOne("project1.Data.datamodel.model1", "model1Data")
                        .WithMany("Examples")
                        .HasForeignKey("Model1Key")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("model1Data");
                });

            modelBuilder.Entity("project1.Data.datamodel.model1", b =>
                {
                    b.Navigation("Examples");
                });
#pragma warning restore 612, 618
        }
    }
}
